name: PlotReviewPlugin
version: 1.12.2.6
description: Review plots
author: Robnoo02
main: me.robnoo02.plotreviewplugin.Main

commands:
  review:
    usage: /<command>
    description: Review cmd
  submit:
    usage: /<command>
    description: Submit your plot
  prdebug:
    usage: /<command>
    description: Debug values